%Reading data from data.txt file, generated by the python script, and assigning them to 
%the respective variables

fp=fopen("../data.txt",'r');
t=importdata("../data.txt",'\t',14);

%import data function returns the first line of the file, which is empty, plus every non-empty line as a string

R1=sscanf(char(t(4,1)), "Values: R1 = %e")*1000;
R2=sscanf(char(t(5,1)), "R2 = %e")*1000;
R3=sscanf(char(t(6,1)), "R3 = %e")*1000;
R4=sscanf(char(t(7,1)), "R4 = %e")*1000;
R5=sscanf(char(t(8,1)), "R5 = %e")*1000;
R6=sscanf(char(t(9,1)), "R6 = %e")*1000;
R7=sscanf(char(t(10,1)), "R7 = %e")*1000;
Vs=sscanf(char(t(11,1)), "Vs = %e");
C=sscanf(char(t(12,1)), "C = %e")/1000000;
Kb=sscanf(char(t(13,1)), "Kb = %e")/1000;
Kd=sscanf(char(t(14,1)), "Kd = %e")*1000;

printf("Data_Gen_TAB\n");
printf("R1 = %e A\n",R1);
printf("R2 = %e A\n",R2);
printf("R3 = %e A\n",R3);
printf("R4 = %e A\n",R4);
printf("R5 = %e A\n",R5);
printf("R6 = %e A\n",R6);
printf("R7 = %e A\n",R7);
printf("Vs = %e A\n",Vs);
printf("C = %e A\n",C);
printf("Kb = %e A\n",Kb);
printf("Kd = %e A\n",Kd);
printf("Data_Gen_END\n");

%Cálculo das Condutâncias

G1=1/R1;
G2=1/R2;
G3=1/R3;
G4=1/R4;
G5=1/R5;
G6=1/R6;
G7=1/R7;
%perguntar se a diretoria utilizada é na boa

fclose(fp);

%PARTE 1


A=[1 0 0 0 0 0 0 0;
-G1 G1+G2+G3 -G2 0 -G3 0 0 0;
0 -Kb-G2 G2 0 Kb 0 0 0;
0 0 0 1 0 0 0 0;
0 -G3 0 -G4 G3+G4+G5 -G5 -G7 G7;
0 Kb 0 0 -Kb-G5 G5 0 0; 
0 0 0 -G6 0 0 G6+G7 -G7;
0 0 0 Kd*G6 -1 0 -Kd*G6 1];

B=[Vs; 0; 0; 0; 0; 0; 0; 0];

V=inv(A)*B; %NODE METHOD RESULTS QUESTION 1

question_1=fopen("question_1.cir","w");

fprintf(question_1,"R1 2 1 %e\n",R1);
fprintf(question_1,"R2 3 2 %e\n",R2);
fprintf(question_1,"R3 2 5 %e\n",R3);
fprintf(question_1,"R4 5 0 %e\n",R4);
fprintf(question_1,"R5 5 6 %e\n",R5);
fprintf(question_1,"R6 0 7 %e\n",R6);
fprintf(question_1,"R7 9 8 %e\n",R7);
fprintf(question_1,"Vs 1 0 %e\n",Vs);
fprintf(question_1,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_1,"Vaux 7 9 0\n");
fprintf(question_1,"Hd 5 8 Vaux %e",Kd);

fclose(question_1);



I1=(V(2)-V(1))*G1;
Ib=(V(2)-V(5))*Kb;
I7=(V(7)-V(8))*G7;
Ic=0;

printf("Voltages_Question_1_TAB\n");
printf("V1 = %e V\n",V(1));
printf("V2 = %e V\n",V(2));
printf("V3 = %e V\n",V(3));
printf("V4 = %e V\n",V(4));
printf("V5 = %e V\n",V(5));
printf("V6 = %e V\n",V(6));
printf("V7 = %e V\n",V(7));
printf("V8 = %e V\n",V(8));
printf("Voltages_Question_1_END\n");

printf("Currents_Question_1_TAB\n");
printf("I1 = %e A\n",I1);
printf("I2 = %e A\n",Ib);
printf("I3 = %e A\n",-(I1-Ib));
printf("I4 = %e A\n",-(I1-I7));
printf("I5 = %e A\n",Ib);
printf("I6 = %e A\n",I7);
printf("I7 = %e A\n",I7);
printf("Is = %e A\n",I1);
printf("Ic = %e A\n",Ic);
printf("Currents_Question_1_END\n");


%PARTE 2

Vx=V(6)-V(8);

E = [1 0 0 0 0 0 0 0 0; 
-G1 G1+G2+G3 -G2 0 -G3 0 0 0 0;
 0 -Kb-G2 G2 0 Kb 0 0 0 0;
 0 -G1 0 0 -G4 0 -G6 0 0;
 0 0 0 0 0 1 0 -1 0;
 0 Kb 0 0 -Kb-G5 G5 0 0 1;
 0 0 0 0 0 0 G6+G7 -G7 0;
 0 0 0 1 0 0 0 0 0;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1 0];

F = [0; 0; 0; 0; Vx; 0; 0; 0; 0];

V2=inv(E)*F;

Req=Vx/V2(9);

tau=Req*C;

question_2=fopen("question_2.cir","w");

fprintf(question_2,"R1 1 2 %e\n",R1);
fprintf(question_2,"R2 3 2 %e\n",R2);
fprintf(question_2,"R3 2 5 %e\n",R3);
fprintf(question_2,"R4 5 0 %e\n",R4);
fprintf(question_2,"R5 5 6 %e\n",R5);
fprintf(question_2,"R6 0 7 %e\n",R6);
fprintf(question_2,"R7 9 8 %e\n",R7);
fprintf(question_2,"Vs 1 0 0\n");
fprintf(question_2,"Vx 6 8 %e\n",Vx);
fprintf(question_2,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_2,"Vaux 7 9 0\n");
fprintf(question_2,"Hd 5 8 Vaux %e",Kd);

fclose(question_2);

printf("Voltages_Question_2_TAB\n");
printf("V1 = %e V\n",V2(1));
printf("V2 = %e V\n",V2(2));
printf("V3 = %e V\n",V2(3));
printf("V4 = %e V\n",V2(4));
printf("V5 = %e V\n",V2(5));
printf("V6 = %e V\n",V2(6));
printf("V7 = %e V\n",V2(7));
printf("V8 = %e V\n",V2(8));
printf("Ix = %e A\n",V2(9));
printf("Req = %e Ohm\n",-Req);
printf("tau = %e \n",-tau);
printf("Voltages_Question_2_END\n");


%PARTE 3

t=0:0.0001:0.02;
V3=Vx*exp((1/(C*Req))*t);

title("Natural Solution, v6n(t)")

fig1=figure(1);
plot(t*1000,V3)
xlabel("Time (ms)");
ylabel("Capacitor Voltage") ;
print(fig1,"naturalsolution","-depsc");

question_3=fopen("question_3.cir","w");

fprintf(question_3,"R1 1 2 %e\n",R1);
fprintf(question_3,"R2 3 2 %e\n",R2);
fprintf(question_3,"R3 2 5 %e\n",R3);
fprintf(question_3,"R4 5 0 %e\n",R4);
fprintf(question_3,"R5 5 6 %e\n",R5);
fprintf(question_3,"R6 0 7 %e\n",R6);
fprintf(question_3,"R7 9 8 %e\n",R7);
fprintf(question_3,"Vs 1 0 0\n");
fprintf(question_3,"C1 6 8 %e\n",C);
fprintf(question_3,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_3,"Vaux 7 9 0\n");
fprintf(question_3,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_3,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_3);


%PARTE 4

f=1000;
w=2*pi*f;
Zc=1/(j*w*C);

G = [1 0 0 -1 0 0 0 0;
 G1 -G1-G2-G3 G2 0 G3 0 0 0;
 0 Kb+G2 -G2 0 -Kb 0 0 0;
 0 0 0 1 0 0 0 0;
 0 G3 0 G4 -G3-G4-G5 G5+1/Zc G7 -G7-1/Zc;
 0 Kb 0 0 -Kb-G5 G5+1/Zc 0 -1/Zc;
 0 0 0 -G6 0 0 G6+G7 -G7;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1];
 
H=[1;0;0;0;0;0;0;0];

V4=inv(G)*H

%Creating complex amplitude table 

printf("Voltages_Amplitudes_TAB\n");
printf("V1 = %e V\n",abs(V4(1)));
printf("V2 = %e V\n",abs(V4(2)));
printf("V3 = %e V\n",abs(V4(3)));
printf("V4 = %e V\n",abs(V4(4)));
printf("V5 = %e V\n",abs(V4(5)));
printf("V6 = %e V\n",abs(V4(6)));
printf("V7 = %e V\n",abs(V4(7)));
printf("V8 = %e V\n",abs(V4(8)));
printf("Voltages_Amplitudes_END\n");

printf("Voltages_Phases_TAB\n");
printf("Phase 1 = %e Radians\n",angle(V4(1)));
printf("Phase 2 = %e Radians\n",angle(V4(2)));
printf("Phase 3 = %e Radians\n",angle(V4(3)));
printf("Phase 4 = %e Radians\n",angle(V4(4)));
printf("Phase 5 = %e Radians\n",angle(V4(5)));
printf("Phase 6 = %e Radians\n",angle(V4(6)));
printf("Phase 7 = %e Radians\n",angle(V4(7)));
printf("Phase 8 = %e Radians\n",angle(V4(8)));
printf("Voltages_Phases_END\n");

%PARTE 5

f=1000;

A=abs(V4(6))
fase=arg(V4(6));

t1=-0.005:0.00001:-0.00001;
t2=0:0.00001:0.02;
t=[t1 t2];
aux=ones(1,length(t1));
y1=Vx*aux;
y2=Vx*exp((1/(C*Req))*t2)+A*sin(2*pi*f*t2+fase); 
y3=Vs*aux;
y4=sin(2*pi*f*t2);


y=[y1 y2];
k=[y3 y4];

fig2=figure(2);
title("V6(t) = V6n(t)+V6f(t)");

plot(t*1000,y,"b")
hold on
plot(t*1000,k,"r")
xlabel("Time (ms)")
ylabel("Voltage (V)")
h=legend({"V6(t)","Vs(t)"});
legend(h,"location","northeast");
print(fig2,"forced_and_natural_solution","-depsc");


question_4=fopen("question_4.cir","w");

fprintf(question_4,"R1 1 2 %e\n",R1);
fprintf(question_4,"R2 3 2 %e\n",R2);
fprintf(question_4,"R3 2 5 %e\n",R3);
fprintf(question_4,"R4 5 0 %e\n",R4);
fprintf(question_4,"R5 5 6 %e\n",R5);
fprintf(question_4,"R6 0 7 %e\n",R6);
fprintf(question_4,"R7 9 8 %e\n",R7);
fprintf(question_4,"Vs 1 0 sin(0V 1V 1k 0 0 0)\n");
fprintf(question_4,"C1 6 8 %e\n",C);
fprintf(question_4,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_4,"Vaux 7 9 0\n");
fprintf(question_4,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_4,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_4);

%PARTE 6

frequencia=logspace(-1,6,200);

for c=1:size(frequencia,2)
  
  Zc= 1/(2*pi*frequencia(c)*C*j);
  
  %matrizes da parte 4
  
  J=[1 0 0 -1 0 0 0 0;
 G1 -G1-G2-G3 G2 0 G3 0 0 0;
 0 Kb+G2 -G2 0 -Kb 0 0 0;
 0 0 0 1 0 0 0 0;
 0 G3 0 G4 -G3-G4-G5 G5+1/Zc G7 -G7-1/Zc;
 0 Kb 0 0 -Kb-G5 G5+1/Zc 0 -1/Zc;
 0 0 0 -G6 0 0 G6+G7 -G7;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1];
  
  L=[1;0;0;0;0;0;0;0];
  
  K=inv(J)*L;
  
  Vc_frequencia(c)=K(6)-K(8);
  V6_frequencia(c)=K(6);
  Vs_frequencia(c)=K(1)-K(4);
  
  
endfor


Vc_y_amp=20*log10(abs(Vc_frequencia));
V6_y_amp=20*log10(abs(V6_frequencia));
Vs_y_amp=20*log10(abs(Vs_frequencia));

Vc_y_ang=angle(Vc_frequencia)*180/pi;
V6_y_ang=angle(V6_frequencia)*180/pi;
Vs_y_ang=angle(Vs_frequencia)*180/pi;


parte6_amplitude = figure();
plot ( log10(frequencia), Vc_y_amp);
hold on;
plot ( log10(frequencia), V6_y_amp);
plot ( log10(frequencia), Vs_y_amp);

xlabel ("Log10(f) (Hz)");
ylabel ("Amplitude (V)" );

ha=legend({"V(c)","V(6)","V(s)"});
legend(ha,"location","northeast");
print(parte6_amplitude,"amplitude","-depsc");

parte6_fase = figure();
plot ( log10(frequencia), Vc_y_ang);
hold on;
plot ( log10(frequencia), V6_y_ang);
plot ( log10(frequencia), Vs_y_ang);

xlabel ("Log10(f) (Hz)");
ylabel ("Fase (V)" );

hb=legend({"V(c)","V(6)","V(s)"});
legend(hb,"location","northeast");
print(parte6_fase,"phase","-depsc");


question_5=fopen("question_5.cir","w");

fprintf(question_5,"R1 1 2 %e\n",R1);
fprintf(question_5,"R2 3 2 %e\n",R2);
fprintf(question_5,"R3 2 5 %e\n",R3);
fprintf(question_5,"R4 5 0 %e\n",R4);
fprintf(question_5,"R5 5 6 %e\n",R5);
fprintf(question_5,"R6 0 7 %e\n",R6);
fprintf(question_5,"R7 9 8 %e\n",R7);
fprintf(question_5,"Vs 1 0 0.0 ac 1.0 sin(0 1 1000)\n");
fprintf(question_5,"C1 6 8 %e\n",C);
fprintf(question_5,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_5,"Vaux 7 9 0\n");
fprintf(question_5,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_5,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_5);

