%Reading data from data.txt file, generated by the python script, and assigning them to 
%the respective variables

fp=fopen("/home/joaomatias/Desktop/ist-tcfe/t2/data.txt",'r');
t=importdata("/home/joaomatias/Desktop/ist-tcfe/t2/data.txt",'\t',14);

%import data function returns the first line of the file, which is empty, plus every non-empty line as a string

R1=sscanf(char(t(4,1)), "Values: R1 = %e")*1000;
R2=sscanf(char(t(5,1)), "R2 = %e")*1000;
R3=sscanf(char(t(6,1)), "R3 = %e")*1000;
R4=sscanf(char(t(7,1)), "R4 = %e")*1000;
R5=sscanf(char(t(8,1)), "R5 = %e")*1000;
R6=sscanf(char(t(9,1)), "R6 = %e")*1000;
R7=sscanf(char(t(10,1)), "R7 = %e")*1000;
Vs=sscanf(char(t(11,1)), "Vs = %e");
C=sscanf(char(t(12,1)), "C = %e")/1000000;
Kb=sscanf(char(t(13,1)), "Kb = %e")/1000;
Kd=sscanf(char(t(14,1)), "Kd = %e")*1000;

%Cálculo das Condutâncias

G1=1/R1;
G2=1/R2;
G3=1/R3;
G4=1/R4;
G5=1/R5;
G6=1/R6;
G7=1/R7;
%perguntar se a diretoria utilizada é na boa

fclose(fp);

%PARTE 1


A=[1 0 0 0 0 0 0 0;
-G1 G1+G2+G3 -G2 0 -G3 0 0 0;
0 -Kb-G2 G2 0 Kb 0 0 0;
0 0 0 1 0 0 0 0;
0 -G3 0 -G4 G3+G4+G5 -G5 -G7 G7;
0 Kb 0 0 -Kb-G5 G5 0 0; 
0 0 0 -G6 0 0 G6+G7 -G7;
0 0 0 Kd*G6 -1 0 -Kd*G6 1];

B=[Vs; 0; 0; 0; 0; 0; 0; 0];

V=inv(A)*B; %NODE METHOD RESULTS QUESTION 1

question_1=fopen("question_1.cir","w");

fprintf(question_1,"R1 2 1 %e\n",R1);
fprintf(question_1,"R2 3 2 %e\n",R2);
fprintf(question_1,"R3 2 5 %e\n",R3);
fprintf(question_1,"R4 5 0 %e\n",R4);
fprintf(question_1,"R5 5 6 %e\n",R5);
fprintf(question_1,"R6 0 7 %e\n",R6);
fprintf(question_1,"R7 9 8 %e\n",R7);
fprintf(question_1,"Vs 1 0 %e\n",Vs);
fprintf(question_1,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_1,"Vaux 7 9 0\n");
fprintf(question_1,"Hd 5 8 Vaux %e",Kd);

fclose(question_1);

%PARTE 2

Vx=V(6)-V(8);

E = [1 0 0 0 0 0 0 0 0; 
-G1 G1+G2+G3 -G2 0 -G3 0 0 0 0;
 0 -Kb-G2 G2 0 Kb 0 0 0 0;
 0 -G1 0 0 -G4 0 -G6 0 0;
 0 0 0 0 0 1 0 -1 0;
 0 Kb 0 0 -Kb-G5 G5 0 0 1;
 0 0 0 0 0 0 G6+G7 -G7 0;
 0 0 0 1 0 0 0 0 0;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1 0];

F = [0; 0; 0; 0; Vx; 0; 0; 0; 0];

V2=inv(E)*F;

Req=Vx/V2(9);

question_2=fopen("question_2.cir","w");

fprintf(question_1,"R1 1 2 %e\n",R1);
fprintf(question_1,"R2 3 2 %e\n",R2);
fprintf(question_1,"R3 2 5 %e\n",R3);
fprintf(question_1,"R4 5 0 %e\n",R4);
fprintf(question_1,"R5 5 6 %e\n",R5);
fprintf(question_1,"R6 0 7 %e\n",R6);
fprintf(question_1,"R7 9 8 %e\n",R7);
fprintf(question_1,"Vs 1 0 0\n");
fprintf(question_1,"Vx 6 8 %e\n",Vx);
fprintf(question_1,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_1,"Vaux 7 9 0\n");
fprintf(question_1,"Hd 5 8 Vaux %e",Kd);


fclose(question_2);


%PARTE 3

t=0:0.0001:0.02;
V3=Vx*exp((1/(C*Req))*t);

title("Natural Solution, v6n(t)")

hold on
figure(1);
plot(t*1000,V3)

xlabel("Time (ms)");
ylabel("Capacitor Voltage") ;

question_3=fopen("question_3.cir","w");

fprintf(question_3,"R1 1 2 %e\n",R1);
fprintf(question_3,"R2 3 2 %e\n",R2);
fprintf(question_3,"R3 2 5 %e\n",R3);
fprintf(question_3,"R4 5 0 %e\n",R4);
fprintf(question_3,"R5 5 6 %e\n",R5);
fprintf(question_3,"R6 0 7 %e\n",R6);
fprintf(question_3,"R7 9 8 %e\n",R7);
fprintf(question_3,"Vs 1 0 0\n");
fprintf(question_3,"C1 6 8 %e\n",C);
fprintf(question_3,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_3,"Vaux 7 9 0\n");
fprintf(question_3,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_3,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_3);


%PARTE 4

f=1000;
w=2*pi*f;
Zc=1/(j*w*C);

G = [1 0 0 -1 0 0 0 0;
 G1 -G1-G2-G3 G2 0 G3 0 0 0;
 0 Kb+G2 -G2 0 -Kb 0 0 0;
 0 0 0 1 0 0 0 0;
 0 G3 0 G4 -G3-G4-G5 G5+1/Zc G7 -G7-1/Zc;
 0 Kb 0 0 -Kb-G5 G5+1/Zc 0 -1/Zc;
 0 0 0 -G6 0 0 G6+G7 -G7;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1];
 
H=[1;0;0;0;0;0;0;0];

V4=inv(G)*H

%Creating complex amplitude table VER MELHOR COM O DO SALITO

printf("Voltages_TAB\n");
printf("V1 = %e\n",abs(V4(1)));
printf("V2 = %e\n",abs(V4(2)));
printf("V3 = %e\n",abs(V4(3)));
printf("V4 = %e\n",abs(V4(4)));
printf("V5 = %e\n",abs(V4(5)));
printf("V6 = %e\n",abs(V4(6)));
printf("V7 = %e\n",abs(V4(7)));
printf("V8 = %e\n",abs(V4(8)));
printf("Voltages_END\n");

%PARTE 5

f=1000;

A=abs(V4(6))
fase=arg(V4(6));

t1=-0.005:0.00001:-0.00001;
t2=0:0.00001:0.02;
t=[t1 t2];
aux=ones(1,length(t1));
y1=Vx*aux;
y2=Vx*exp((1/(C*Req))*t2)+A*sin(2*pi*f*t2+fase); 
y3=Vs*aux;
y4=sin(2*pi*f*t2);


y=[y1 y2];
k=[y3 y4];

figure(2);
title("V6(t) = V6n(t)+V6f(t)");

hold on

plot(t*1000,y,"b")
plot(t*1000,k,"r")
xlabel("Time (ms)")
ylabel("Voltage (V)")
h=legend({"V6(t)","Vs(t)"});
legend(h,"location","northeast");


question_4=fopen("question_4.cir","w");

fprintf(question_4,"R1 1 2 %e\n",R1);
fprintf(question_4,"R2 3 2 %e\n",R2);
fprintf(question_4,"R3 2 5 %e\n",R3);
fprintf(question_4,"R4 5 0 %e\n",R4);
fprintf(question_4,"R5 5 6 %e\n",R5);
fprintf(question_4,"R6 0 7 %e\n",R6);
fprintf(question_4,"R7 9 8 %e\n",R7);
fprintf(question_4,"Vs 1 0 sin(0V 1V 1k 0 0 0)\n");
fprintf(question_4,"C1 6 8 %e\n",C);
fprintf(question_4,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_4,"Vaux 7 9 0\n");
fprintf(question_4,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_4,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_4);

%PARTE 6

frequencia=logspace(-1,6,200);

for c=1:size(frequencia,2)
  
  w(c)=2*pi*frequencia(c);
  
  Zc= 1/(2*pi*frequencia(c)*C*j);
  
  %matrizes da parte 4
  
  J=[1 0 0 -1 0 0 0 0;
 G1 -G1-G2-G3 G2 0 G3 0 0 0;
 0 Kb+G2 -G2 0 -Kb 0 0 0;
 0 0 0 1 0 0 0 0;
 0 G3 0 G4 -G3-G4-G5 G5+1/Zc G7 -G7-1/Zc;
 0 Kb 0 0 -Kb-G5 G5+1/Zc 0 -1/Zc;
 0 0 0 -G6 0 0 G6+G7 -G7;
 0 0 0 Kd*G6 -1 0 -Kd*G6 1];
  
  L=[1;0;0;0;0;0;0;0];
  
  K=inv(J)*L;
  
  Vc_frequencia(c)=K(6)-K(8);
  V6_frequencia(c)=K(6);
  Vs_frequencia(c)=K(1)-K(4);
  
  w_x=log10(w);
endfor


Vc_y_amp=20*log10(abs(Vc_frequencia));
V6_y_amp=20*log10(abs(V6_frequencia));
Vs_y_amp=20*log10(abs(Vs_frequencia));

Vc_y_ang=angle((Vc_frequencia*180)/pi);
V6_y_ang=angle((V6_frequencia*180)/pi);
Vs_y_ang=angle((Vs_frequencia*180)/pi);

parte6_amplitude = figure();
plot ( w_x, Vc_y_amp);
hold on;
plot ( w_x, V6_y_amp);
plot ( w_x, Vs_y_amp);

xlabel ("Log10(w) (rad/s)");
ylabel ("Amplitude (V)" );

ha=legend({"V(c)","V(6)","V(s)"});
legend(ha,"location","northeast");

parte6_fase = figure();
plot ( w_x, Vc_y_ang);
hold on;
plot ( w_x, V6_y_ang);
plot ( w_x, Vs_y_ang);

xlabel ("Log10(w) (rad/s)");
ylabel ("Fase (V)" );

hb=legend({"V(c)","V(6)","V(s)"});
legend(hb,"location","northeast");


question_5=fopen("question_5.cir","w");

fprintf(question_5,"R1 1 2 %e\n",R1);
fprintf(question_5,"R2 3 2 %e\n",R2);
fprintf(question_5,"R3 2 5 %e\n",R3);
fprintf(question_5,"R4 5 0 %e\n",R4);
fprintf(question_5,"R5 5 6 %e\n",R5);
fprintf(question_5,"R6 0 7 %e\n",R6);
fprintf(question_5,"R7 9 8 %e\n",R7);
fprintf(question_5,"Vs 1 0 0.0 ac 1.0 sin(0 1 1000)\n");
fprintf(question_5,"C1 6 8 %e\n",C);
fprintf(question_5,"Gb 6 3 (2,5) %e\n",Kb);
fprintf(question_5,"Vaux 7 9 0\n");
fprintf(question_5,"Hd 5 8 Vaux %e\n",Kd);

fprintf(question_5,".IC v(6)=%e v(8)=%e",V(6),V(8));


fclose(question_5);

